Do_An_Wed/Areas/Admin/Controllers/KhachhangController.cs
using Do_An_Wed.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Do_An_Wed.Areas.Admin.Controllers
{
    public class KhachhangController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        ///quản lý khách hàng
        #region QUAN LY TAI KHOAN KHACH HANG
        public ActionResult QLKhachhang(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 4;
            return View(data.KHACHHANGs.Where(n => n.MaRole == 0).ToList().ToPagedList(pageNumber, pageSize));
        }
        //Xóa khách hàng
        [HttpGet]
        public ActionResult Xoatkkh(int id)
        {
            KHACHHANG tk = data.KHACHHANGs.Where(n => n.MaRole == 0).SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaKH = tk.MaKH;
            return View(tk);
        }
        [HttpPost, ActionName("Xoatkkh")]
        public ActionResult AcXoatkkh(int id)
        {
            KHACHHANG tk = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaKH = tk.MaKH;
            data.KHACHHANGs.DeleteOnSubmit(tk);
            data.SubmitChanges();
            return RedirectToAction("QLKhachhang");
        }
        //chi tiết khách hàng

        public ActionResult Chitietkh(int id)
        {
            KHACHHANG kh = data.KHACHHANGs.Where(n => n.MaRole == 0).SingleOrDefault(n => n.MaKH == id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MAKH = kh.MaKH;
            return View(kh);
        }
        /// sửa khach hàng
        [HttpGet]
        public ActionResult Suakh(int id)
        {
            ViewBag.maQuyen = new SelectList(data.Roles.ToList().OrderBy(n => n.MaRole), "MaRole", "TenRole");
            KHACHHANG tk = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(tk);
        }
        [HttpPost, ActionName("Suakh")]
        [ValidateInput(false)]
        public ActionResult savekh(int id)
        {
            KHACHHANG tk = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            UpdateModel(tk);
            data.SubmitChanges();
            return RedirectToAction("QLKhachhang");
        }
        #endregion
    }
}

Do_An_Wed/Areas/Admin/Views/Khachhang/Chitietkh.cshtml
@model Do_An_Wed.Models.KHACHHANG

@{
    ViewBag.Title = "Chitietkh";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-md-6 card border rounded-4">
            <h2 class="text-center">Chi tiết khách hàng</h2>
            <hr />

            <dl class="row">
                <dt class="col-sm-3">Họ tên:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.HoTen)</dd>
                <dt class="col-sm-3">Tên tài khoản:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.tentk)</dd>

                <dt class="col-sm-3">số điện thoại:</dt>
                <dd class="col-sm-9"> @Html.DisplayFor(model => model.DienthoaiKh) </dd>
                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.EmailKH)</dd>
                <dt class="col-sm-3">Địa chỉ:</dt>
                <dd class="col-sm-9"> @Html.DisplayFor(model => model.DiachiKH) </dd>
             

            </dl>
            <div class="text-center">
                @Html.ActionLink("Back to page", "QLKhachhang", null, new { @class = "btn btn-primary btn-xs" })
                @Html.ActionLink("Edit", "Suakh", new { id = Model.MaKH }, new { @class = "btn btn-danger btn-xs" })
            </div>
        </div>
    </div>
</div>

<style>
    dt {
        font-weight: bold;
    }

    hr {
        border-color: #999999;
    }
</style>

Do_An_Wed/Areas/Admin/Views/Khachhang/QLKhachhang.cshtml
@using PagedList.Mvc;
@using Do_An_Wed.Models
@model PagedList.PagedList<Do_An_Wed.Models.KHACHHANG>

@{
    ViewBag.Title = "QLKhachhang";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<link href="~/Content/Admin/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
<h2 style="font-weight: bold; margin-bottom: 35px;margin-top:30px">DANH SÁCH KHACH HANG</h2>

<div class="x_panel">
    <div class="x_title">
      
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <p></p>
        <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
                <thead>
                    <tr class="headings">
                        <th>
                            <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" id="check-all" class="flat" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                        </th>
                        <th class="column-title">Tên tài khoản </th>
                        <th class="column-title">Mã tài khoản </th>
                        <th class="column-title">Tên khách hàng </th>
                        <th class="column-title">Địa chỉ  </th>
                        <th class="column-title">Email </th>
                        <th class="column-title">Điện thoại </th>
                        <th class="column-title no-link last">
                            <span class="nobr">Chức năng</span>
                        </th>
                        <th class="bulk-actions" colspan="7">
                            <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
         
                    @foreach (var item in Model)
                    {
                        <tr class="odd pointer">
                            <td class="a-center ">
                                <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" class="flat" name="table_records" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tentk)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.mk)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HoTen)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DiachiKH)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmailKH)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DienthoaiKh)
                            </td>
                          

                            <td>
                                <a href="@Url.Action("Chitietkh","Khachhang",new { id = item.MaKH})" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="@Url.Action("Suakh","Khachhang",new { id = item.MaKH})" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="@Url.Action("Xoatkkh","Khachhang",new { id = item.MaKH})" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="d-flex justify-content-center">
    @Html.PagedListPager(Model, page => Url.Action("QLKhachhang", new { page = page }), new PagedListRenderOptions { LiElementClasses = new string[] { "page-item btn btn-sm btn-primary mx-1" } })
</div>

Do_An_Wed/Areas/Admin/Views/Khachhang/Suakh.cshtml
@model Do_An_Wed.Models.KHACHHANG

@{
    ViewBag.Title = "Suakh";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>CHỈNH SỬA THÔNG TIN KHÁCH HÀNG</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiachiKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiachiKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiachiKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienthoaiKh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienthoaiKh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienthoaiKh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tentk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tentk, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tentk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mk, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mk, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10" style="padding-top:30px;">
                            <a href="@Url.Action("QLKhachhang","Khachhang")" class="btn btn-primary btn-xs">Back to List</a>
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Do_An_Wed/Areas/Admin/Views/Khachhang/Xoatkkh.cshtml
@model Do_An_Wed.Models.KHACHHANG

@{
    ViewBag.Title = "Xoatkkh";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-md-6 card border rounded-4">
            <h2 class="text-center">XOÁ THÔNG TIN KHÁCH HÀNG</h2>
            <hr />
            <dl class="row">
                <dt class="col-sm-4">Họ tên:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.HoTen)</dd>

                <dt class="col-sm-4">Địa chỉ:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.DiachiKH)</dd>

                <dt class="col-sm-4">Email:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.EmailKH)</dd>

                <dt class="col-sm-4">Điện thoại:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.DienthoaiKh)</dd>

                <dt class="col-sm-4">Tên tài khoản:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.tentk)</dd>

                <dt class="col-sm-4">Mật khẩu:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.mk)</dd>

                
            </dl>
            <div class="text-center">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-danger btn-xs" />
                        @Html.ActionLink("Back to List", "QLKhachhang", null, new { @class = "btn btn-primary btn-xs" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>