Do_An_Wed/Areas/Admin/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Do_An_Wed.Models;
using PagedList;

namespace Do_An_Wed.Areas.Admin.Controllers
{
    public class AdminController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult Index()
        {
            List<SANPHAM> list = data.SANPHAMs.ToList();
            int v = list.Count();
            List<DANHMUC> dm = data.DANHMUCs.ToList();
            int d = dm.Count();
            List<THUONGHIEU> listth = data.THUONGHIEUs.ToList();
            int t = listth.Count();
            List<KHACHHANG> TK = data.KHACHHANGs.Where(n => n.MaRole == 0).ToList();
            List<KHACHHANG> TKad = data.KHACHHANGs.Where(n => n.MaRole == 1).ToList();
            ViewBag.sanpham = v;
            ViewBag.dm = d;
            ViewBag.thuonghieu = t;
            ViewBag.khachhang = TK.Count();
            ViewBag.Admin = TKad.Count();
            
            return View();
        }
     
        ///quản lý admin

        #region QUẢN LÝ THÔNG TIN ADMIN
        public ActionResult QLAdmin(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 4;
            return View(data.KHACHHANGs.Where(n => n.MaRole == 1).ToList().ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult themad()
        {

            ViewBag.MaRole = new SelectList(data.Roles.ToList().OrderBy(n => n.MaRole), "MaRole", "TenRole");
            return View();
        }
        [HttpPost]
        
        public ActionResult Themad(KHACHHANG taikhoa)
        {
            if (string.IsNullOrEmpty(taikhoa.tentk))
            {
                ViewBag.ThongBao = "Bạn cần nhập tên thương hiệu";
                return View(taikhoa.tentk);
            }
            KHACHHANG brand = data.KHACHHANGs.FirstOrDefault(b => b.tentk == taikhoa.tentk);
            if (brand != null)
            {
                ViewBag.ThongBao = "Tên thương hiệu đã tồn tại";
                return View(taikhoa);
            }
            ViewBag.MaRole = new SelectList(data.Roles.ToList().OrderBy(n => n.MaRole), "MaRole", "TenRole");
            data.KHACHHANGs.InsertOnSubmit(taikhoa);
            data.SubmitChanges();
            return RedirectToAction("QLAdmin");
        }
        [HttpGet]
        public ActionResult Suaad(int id)
        {
            ViewBag.maQuyen = new SelectList(data.Roles.ToList().OrderBy(n => n.MaRole), "MaRole", "TenRole");
            KHACHHANG tk = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(tk);
        }
        [HttpPost, ActionName("Suaad")]
        [ValidateInput(false)]
        public ActionResult savead(int id)
        {
            KHACHHANG tk = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            UpdateModel(tk);
            data.SubmitChanges();
            return RedirectToAction("QLAdmin");
        }
        [HttpGet]
        public ActionResult Xoaad(int id)
        {
            KHACHHANG tk = data.KHACHHANGs.Where(n => n.MaRole == 1).SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaKH = tk.MaKH;
            return View(tk);
        }
        [HttpPost, ActionName("Xoaad")]
        public ActionResult upxoaad(int id)
        {
            KHACHHANG tk = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (tk == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaKH = tk.MaKH;
            data.KHACHHANGs.DeleteOnSubmit(tk);
            data.SubmitChanges();
            return RedirectToAction("QLAdmin");
        }
        //chi tiết khách hàng

        public ActionResult Chitietad(int id)
        {
            KHACHHANG kh = data.KHACHHANGs.Where(n => n.MaRole == 1).SingleOrDefault(n => n.MaKH == id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MAKH = kh.MaKH;
            return View(kh);
        }

     
        #endregion



    }
}

Do_An_Wed/Areas/Admin/Controllers/DanhmucController.cs
using Do_An_Wed.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Do_An_Wed.Areas.Admin.Controllers
{
    public class DanhmucController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: Admin/Danhmuc
        //quản lý danh mục
        #region quản ly Danh mục
        public ActionResult QLDanhmuc(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 4;
            return View(data.DANHMUCs.ToList().OrderBy(n => n.MaDM).ToPagedList(pageNumber, pageSize));
        }
        //Them danh mục
        [HttpGet]
        public ActionResult Themmoidm()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Themmoidm(DANHMUC danhmuc)
        {
            if (string.IsNullOrEmpty(danhmuc.TenDM))
            {
                ViewBag.ThongBao = "Bạn cần nhập tên danh mục";
                return View(danhmuc.TenDM);
            }
            var brand = data.DANHMUCs.FirstOrDefault(b => b.TenDM == danhmuc.TenDM);
            if (brand != null)
            {
                ViewBag.ThongBao = "Tên danh mục đã tồn tại";
                return View(danhmuc);
            }


            // Lưu thương hiệu vào CSDL ở đây


            data.DANHMUCs.InsertOnSubmit(danhmuc);
            data.SubmitChanges();
            return RedirectToAction("QLDanhmuc");
        }

        //xoa danh muc
        [HttpGet]
        public ActionResult Xoadm(int id)
        {
            DANHMUC dm = data.DANHMUCs.SingleOrDefault(n => n.MaDM == id);
            if (dm == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.idDM = dm.MaDM;
            return View(dm);

        }
        [HttpPost, ActionName("Xoadm")]
        public ActionResult AcceptXoaDM(int id)
        {
            DANHMUC dm = data.DANHMUCs.SingleOrDefault(n => n.MaDM == id);
            if (dm == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.idDM = dm.MaDM;
            data.DANHMUCs.DeleteOnSubmit(dm);
            data.SubmitChanges();
            return RedirectToAction("QLDanhmuc");
        }
        //sua danh muc
        [HttpGet]
        public ActionResult Suadm(int id)
        {
            DANHMUC danhmuc = data.DANHMUCs.SingleOrDefault(n => n.MaDM == id);
            if (danhmuc == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(danhmuc);
        }
        [HttpPost, ActionName("Suadm")]
        [ValidateInput(false)]
        public ActionResult save(int id)
        {

            DANHMUC danhmuc = data.DANHMUCs.SingleOrDefault(n => n.MaDM == id);
            if (danhmuc == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            ViewBag.MaTS = danhmuc.MaDM;
            UpdateModel(danhmuc);
            data.SubmitChanges();
            return RedirectToAction("QLDanhmuc");
        }
        #endregion
    }
}

Do_An_Wed/Areas/Admin/Controllers/DonhangController.cs
using Do_An_Wed.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Do_An_Wed.Areas.Admin.Controllers
{
    public class DonhangController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: Admin/Donhang
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 7;
            return View(data.DONHANGs.ToList().OrderBy(n => n.MaDH).ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult SuaDH(int id)
        {

            DONHANG sanpham = data.DONHANGs.SingleOrDefault(n => n.MaDH == id);
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanpham);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaDH(DONHANG sanpham)
        {
            DONHANG sp = data.DONHANGs.FirstOrDefault(x => x.MaDH == sanpham.MaDH);
            sp.NgayDH = sanpham.NgayDH;
            sp.Ngaygiao = sanpham.Ngaygiao;
            sp.Trangthai = sanpham.Trangthai;          
            UpdateModel(sp);
            data.SubmitChanges();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult XoaDH(int id)
        {
            var sanpham = data.DONHANGs.First(n => n.MaDH == id);
            ViewBag.MaSP = sanpham.MaDH;
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanpham);
        }
        [HttpPost, ActionName("XoaDH")]
        public ActionResult XacnhanxoaDH(int id, FormCollection collection)
        {
            var sanpham = data.DONHANGs.SingleOrDefault(n => n.MaDH == id);
            ViewBag.MaSP = sanpham.MaDH;
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.DONHANGs.DeleteOnSubmit(sanpham);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ChitietDH(int id)
        {
            DONHANG thuonghieu = data.DONHANGs.SingleOrDefault(n => n.MaDH == id);
            ViewBag.MaTH = thuonghieu.MaDH;
            if (thuonghieu == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(thuonghieu);
        }

    }
}

Do_An_Wed/Areas/Admin/Controllers/SanphamController.cs
using Do_An_Wed.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Do_An_Wed.Areas.Admin.Controllers
{
    public class SanphamController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        /// quản lý sản phẩm

        #region QUẢN LÝ SẢN PHẨM
        public ActionResult QLSanpham(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 7;
            return View(data.SANPHAMs.ToList().OrderBy(n => n.MaSP).ToPagedList(pageNumber, pageSize));
        }
        // the moi san pham
        [HttpGet]
        public ActionResult Themmoisp()
        {
            ViewBag.MaTH = new SelectList(data.THUONGHIEUs.ToList().OrderBy(n => n.TenTH), "MaTH", "TenTH");
            ViewBag.MaDM = new SelectList(data.DANHMUCs.ToList().OrderBy(n => n.TenDM), "MaDM", "TenDM");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Themmoisp(SANPHAM sanpham, HttpPostedFileBase uploadhinh)
        {

            data.SANPHAMs.InsertOnSubmit(sanpham);
            data.SubmitChanges();
            if (uploadhinh != null && uploadhinh.ContentLength > 0)
            {
                int id = int.Parse(data.SANPHAMs.ToList().Last().MaSP.ToString());

                string _FileName = "";
                int index = uploadhinh.FileName.IndexOf('.');
                _FileName = "themsp" + id.ToString() + "." + uploadhinh.FileName.Substring(index + 1);
                string _path = Path.Combine(Server.MapPath("~/Content/img"), _FileName);
                uploadhinh.SaveAs(_path);

                SANPHAM unv = data.SANPHAMs.FirstOrDefault(x => x.MaSP == id);
                unv.HinhanhSP = _FileName;
                data.SubmitChanges();
            }
            return RedirectToAction("QLSanpham");

        }

        //hien thi san pham
        public ActionResult Chitietsp(int id)
        {
            SANPHAM sanpham = data.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
            ViewBag.MaSP = sanpham.MaSP;
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanpham);
        }

        //xoa san pham
        [HttpGet]
        public ActionResult Xoasp(int id)
        {
            SANPHAM sanpham = data.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
            ViewBag.MaSP = sanpham.MaSP;
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanpham);
        }
        [HttpPost, ActionName("Xoasp")]
        public ActionResult Xacnhanxoa(int id)
        {
            SANPHAM sanpham = data.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
            ViewBag.MaSP = sanpham.MaSP;
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.SANPHAMs.DeleteOnSubmit(sanpham);
            data.SubmitChanges();
            return RedirectToAction("QLSanpham");
        }
        //chỉnh sửa sản phẩm
        // chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult Suasp(int id)
        {

            SANPHAM sanpham = data.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaTH = new SelectList(data.THUONGHIEUs.ToList().OrderBy(n => n.MaTH), "MaTH", "TenTH");
            ViewBag.MaDM = new SelectList(data.DANHMUCs.ToList().OrderBy(n => n.MaDM), "MaDM", "TenDM");
            return View(sanpham);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Suasp(SANPHAM sanpham, HttpPostedFileBase uploadhinh)
        {
            ViewBag.MaTH = new SelectList(data.THUONGHIEUs.ToList().OrderBy(n => n.MaTH), "MaTH", "TenTH");
            ViewBag.MaDM = new SelectList(data.DANHMUCs.ToList().OrderBy(n => n.MaDM), "MaDM", "TenDM");
            SANPHAM sp = data.SANPHAMs.FirstOrDefault(x => x.MaSP == sanpham.MaSP);
            sp.TenSP = sanpham.TenSP;
            sp.MotaSP = sanpham.MotaSP;

            if (uploadhinh != null && uploadhinh.ContentLength > 0)
            {
                int id = sanpham.MaSP;

                string _FileName = "";
                int index = uploadhinh.FileName.IndexOf('.');
                _FileName = "suasp" + id.ToString() + "." + uploadhinh.FileName.Substring(index + 1);
                string _path = Path.Combine(Server.MapPath("~/Content/img"), _FileName);
                uploadhinh.SaveAs(_path);
                sp.HinhanhSP = _FileName;
            }

            sp.NgaycapnhatSP = sanpham.NgaycapnhatSP;
            sp.SoluongSP = sanpham.SoluongSP;
            sp.GiaSP = sanpham.GiaSP;
            sp.MaTH = 1;
            sp.MaDM = 1;
            UpdateModel(sp);
            data.SubmitChanges();    
            return RedirectToAction("QLSanpham");
            
        }
        #endregion
    }
}

Do_An_Wed/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gentelella Alela! | </title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Scripts/nprogress/nprogress.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />
    <script src="~/Scripts/daterangepicker.js"></script>
    <link href="~/Content/custom.min.css" rel="stylesheet" />
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>


    <script src="/path/or/uri/to/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinyMCE.init({
            mode: "textareas"
           
        });
    </script>
</head>


<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="@Url.Action("Index","Admin")" class="site_title"><i class="fa fa-bug"></i> <span>Trang Admin</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                       
                        <div class="profile_info">
                            <p>Welcome, <span class="fw-bold text-light">@Session["Tendangnhap"]</span></p>   
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a href="@Url.Action("Index","Admin")">
                                        <i class="fa fa-home"></i> <span>Trang Chủ</span>
                                     </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("QLAdmin","Admin")"><i class="fa fa-user"></i> <span> Quản lý Admin</span> </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("QLKhachhang","Khachhang")"><i class="fa fa-users"></i> <span> Quản lý khách hàng</span></a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","Donhang")"><i class="fa fa-cubes"></i> <span>Quản lý đơn hàng</span></a>
                                </li>
                                <li>
                                    <a href="@Url.Action("QLSanpham","Sanpham")"><i class="fa fa-leaf"></i> <span>Quản lý sản phẩm</span></a>
                                </li>
                                <li>
                                    <a href="@Url.Action("QLDanhmuc","Danhmuc")"><i class="fa fa-tags"></i> <span>Quản lý danh mục</span></a>
                                </li>
                                <li>
                                    <a href="@Url.Action("QLThuonghieu","Thuonghieu")"><i class="fa fa-paw"></i> <span>Quản lý thương hiệu</span></a>
                                </li>

                            </ul>
                      
                        </div>
                        

                    </div>
                  
                  
                </div>
            </div>

            <!-- top navigation -->
            <div class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="d-flex w-100 align-items-center justify-content-end mx-2">
                    <div> </div>
                    <div onclick="addActiveClass()"
                         class="nav-item dropdown show" style="padding-left: 15px;">
                        <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="true">
                            @Session["TaiKhoan"]
                        </a>
                        <div class="dropdown-menu dropdown-usermenu pull-right dimem" id="dimem" aria-labelledby="navbarDropdown" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-89px, 20px, 0px);">
                            <a class="dropdown-item" href="javascript:;"> @Html.ActionLink("Profile", "Chitietadadmin", new { id = Session["TaiKhoan"]}) </a>
                            <a class="dropdown-item" href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                            <a class="dropdown-item" href="javascript:;">Help</a>
                            <a class="dropdown-item" href="/Account/Logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                        </div>
                    </div>
                </div>
            </div>
           
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main" style=" min-height: 900.8px;">
                <div class="">

                    @RenderBody()
                </div>
             </div>
                    <!-- /page content -->
                   
                </div>
            </div>

     
            <script>function addActiveClass() {
    var element = document.getElementById("dimem");
    if (element.classList.contains("show")) {
        element.classList.remove("show");
    } else {
        element.classList.add("show");
    }

                }</script>
</body>
</html>