Do_An_Wed/Models/Giohang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Do_An_Wed.Models
{
    public class Giohang
    {
        MyDataDataContext data = new MyDataDataContext();

        public int Masp { get; set; }

        public string tensanpham { get; set; }

        public string hinh { get; set; }

        public int giaban { get; set; }

        public int soluong { get; set; }

        public double dThanhTIen
        {
            get { return soluong * giaban; }
        }

        public Giohang(int id)
        {
            Masp = id;
            SANPHAM sp = data.SANPHAMs.Single(n => n.MaSP == Masp);
            tensanpham = sp.TenSP;
            hinh = sp.HinhanhSP;
            giaban = (int)double.Parse(sp.GiaSP.ToString());
            soluong = 1;
        }
    }
}

Do_An_Wed/Controllers/GioHangController.cs
using Do_An_Wed.Models;
using Do_An_Wed.Momo;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace Do_An_Wed.Controllers
{
    public class GioHangController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: Giohang
        public List<Giohang> Laygiohang()
        {
            List<Giohang> lstgiohang = Session["Giohang"] as List<Giohang>;
            if (lstgiohang == null)
            {
                lstgiohang = new List<Giohang>();
                Session["Giohang"] = lstgiohang;
            }

            return lstgiohang;
        }
        public ActionResult ThemGioHang(int id, string strURL)
        {
            List<Giohang> lstgiohang = Laygiohang();
            Giohang sanpham = lstgiohang.Find(n => n.Masp == id);
            if (sanpham == null)
            {
                sanpham = new Giohang(id);
                lstgiohang.Add(sanpham);
                Session["TongSoSp"] = TongSoluongSanPham() + "";
                return Redirect(strURL);
            }
            else
            {
                Session["TongSoSp"] = TongSoluongSanPham() + "";
                sanpham.soluong++;
                return Redirect(strURL);
            }
        }
        private int TongSoluong()
        {
            int tsl = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                tsl = lstGiohang.Sum(n => n.soluong);
            }
            return tsl;
        }

        private int TongSoluongSanPham()
        {
            int tsl = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                tsl = lstGiohang.Count;
            }
            Session["TongSoSp"] = tsl + "";
            return tsl;
        }

        private double TongTien()
        {
            double tt = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                tt = lstGiohang.Sum(n => n.dThanhTIen);
            }
            return tt;
        }
        public ActionResult Giohang()
        {
            List<Giohang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = TongSoluong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoluongSanPham();
            Session["TongSoSp"] = TongSoluongSanPham() + "";
            return View(lstGiohang);
        }

        public ActionResult GiohangPartial()
        {
            ViewBag.Tongsoluong = TongSoluong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoluongSanPham();
            Session["TongSoSp"] = TongSoluongSanPham() + "";
            return PartialView();
        }

        public ActionResult XoaGioHang(int id)
        {
            List<Giohang> lstGiohang = Laygiohang();
            Giohang sanpham = lstGiohang.SingleOrDefault(n => n.Masp == id);
            if (sanpham != null)
            {
                lstGiohang.RemoveAll(n => n.Masp == id);
                return RedirectToAction("Giohang");
            }
            return RedirectToAction("Giohang");
        }

        public ActionResult Cannhapgiohang(int id, FormCollection collection)
        {
            List<Giohang> lstGiohang = Laygiohang();
            Giohang sanpham = lstGiohang.SingleOrDefault(n => n.Masp == id);
            if (sanpham != null)
            {
                sanpham.soluong = int.Parse(collection["txtSolg"].ToString());
            }
            return RedirectToAction("Giohang");
        }

        public ActionResult Xoatatcagiohang()
        {
            List<Giohang> lstGiohang = Laygiohang();
            lstGiohang.Clear();
            return RedirectToAction("Giohang");
        }

        [HttpGet]
        public ActionResult DatHang()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Login", "Account");
            }
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("sanpham", "sanphams");
            }
            List<Giohang> lstGioHang = Laygiohang();
            ViewBag.Tongsoluong = TongSoluong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoluongSanPham();
            return View(lstGioHang);
        }
        public ActionResult DatHang(FormCollection collection)
        {
            DONHANG dh = new DONHANG();
            KHACHHANG kh = (KHACHHANG)Session["TaikhoanCart"];

            List<Giohang> gh = Laygiohang();

            var ngaygiao = String.Format("{0:dd/MM/yyyy}", collection["NgayGiao"]);
            dh.MaKH = kh.MaKH;
            dh.NgayDH = DateTime.Now;
            dh.Ngaygiao = DateTime.Parse(ngaygiao);
            dh.Trangthai = false;

            data.DONHANGs.InsertOnSubmit(dh);
            data.SubmitChanges();
            foreach (var item in gh)
            {
                CHITIETDONHANG ctdh = new CHITIETDONHANG();
                ctdh.MaDH = dh.MaDH;
                ctdh.MaSP = item.Masp;
                ctdh.Soluong = item.soluong;
                ctdh.Dongia = (decimal)item.giaban;
                //s = data.SANPHAMs.Single(n => n.MaSP == item.Masp);
                //s.soluongton -= ctdh.soluong;               
                data.CHITIETDONHANGs.InsertOnSubmit(ctdh);
                data.SubmitChanges();
            }
            
            data.SubmitChanges();
            Session["GioHang"] = null;

            return RedirectToAction("XacNhanDonHang", "GioHang");
        }

        public ActionResult XacNhanDonHang()
        {
            return View();
        }

        //public ActionResult Payment()
        //{
        //    //request params need to request to MoMo system
        //    List<Giohang> giohangs = Session["GioHang"] as List<Giohang>;
        //    string endpoint = "https://test-payment.momo.vn/gw_payment/transactionProcessor";
        //    string partnerCode = ConfigurationManager.AppSettings["partnerCode"].ToString();
        //    string accessKey = ConfigurationManager.AppSettings["accessKey"].ToString();
        //    string serectKey = ConfigurationManager.AppSettings["serectKey"].ToString();
        //    string orderInfo = "DH" + DateTime.Now.ToString("yyyyMMddHHmmss");
        //    string returnUrl = ConfigurationManager.AppSettings["returnUrl"].ToString();
        //    string notifyurl = ConfigurationManager.AppSettings["notifyurl"].ToString();

        //    string amount = giohangs.Sum(n => n.dThanhTIen).ToString();
        //    string orderid = Guid.NewGuid().ToString();
        //    string requestId = Guid.NewGuid().ToString();
        //    string extraData = "";

        //    //Before sign HMAC SHA256 signature
        //    string rawHash = "partnerCode=" +
        //        partnerCode + "&accessKey=" +
        //        accessKey + "&requestId=" +
        //        requestId + "&amount=" +
        //        amount + "&orderId=" +
        //        orderid + "&orderInfo=" +
        //        orderInfo + "&returnUrl=" +
        //        returnUrl + "&notifyUrl=" +
        //        notifyurl + "&extraData=" +
        //        extraData;

        //    MoMoSecurity crypto = new MoMoSecurity();
        //    //sign signature SHA256
        //    string signature = crypto.signSHA256(rawHash, serectKey);

        //    //build body json request
        //    JObject message = new JObject
        //    {
        //        { "partnerCode", partnerCode },
        //        { "accessKey", accessKey },
        //        { "requestId", requestId },
        //        { "amount", amount },
        //        { "orderId", orderid },
        //        { "orderInfo", orderInfo },
        //        { "returnUrl", returnUrl },
        //        { "notifyUrl", notifyurl },
        //        { "extraData", extraData },
        //        { "requestType", "captureMoMoWallet" },
        //        { "signature", signature }

        //    };

        //    string responseFromMomo = PaymentRequest.sendPaymentRequest(endpoint, message.ToString());

        //    JObject jmessage = JObject.Parse(responseFromMomo);

        //    return Redirect(jmessage.GetValue("payUrl").ToString());
        //}

        ////Khi thanh toán xong ở cổng thanh toán Momo, Momo sẽ trả về một số thông tin, trong đó có errorCode để check thông tin thanh toán
        ////errorCode = 0 : thanh toán thành công (Request.QueryString["errorCode"])
        ////Tham khảo bảng mã lỗi tại: https://developers.momo.vn/#/docs/aio/?id=b%e1%ba%a3ng-m%c3%a3-l%e1%bb%97i
        //public ActionResult ConfirmPaymentClient(Result result)
        //{
        //    //lấy kết quả Momo trả về và hiển thị thông báo cho người dùng (có thể lấy dữ liệu ở đây cập nhật xuống db)
        //    string rMessage = result.message;
        //    string rOrderId = result.orderId;
        //    string rErrorCode = result.errorCode; // = 0: thanh toán thành công
        //    return View();
        //}

        //[HttpPost]
        //public void SavePayment()
        //{
        //    //cập nhật dữ liệu vào db
        //    String a = "";
        //}
    }
}

Do_An_Wed/Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Do_An_Wed.Models;
using PagedList;

namespace Do_An_Wed.Controllers
{
    public class SanphamsController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult sanpham(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 6;
            return View(data.SANPHAMs.ToList().OrderBy(n => n.MaSP).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Chitiet(int id)
        {
            var chitiet = from s in data.SANPHAMs
                         where s.MaSP == id
                         select s;
            return View(chitiet.Single());
        }
        // 
        /// 
        /// SẢN PHẨM SẮP XẾP THEO DANH MỤC
      
        public ActionResult Danhmuc()
        {
            var danhmuc = from dm in data.DANHMUCs select dm;
            return PartialView(danhmuc);
        }
        public ActionResult SPTheodanhmuc(int id, int? page)
        {
            // kiem tra thuong hieu co ton tai khong
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            DANHMUC danhmuc = data.DANHMUCs.SingleOrDefault(n => n.MaDM == id);
            if (danhmuc == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //truy xuat danh sach theo thuong hieu
            List<SANPHAM> listsanpham = data.SANPHAMs.Where(n => n.MaDM == id).OrderBy(n => n.GiaSP).ToList();
            if (listsanpham.Count == 0)
            {
                ViewBag.sanpham = "Thương hiệu này chưa mở bán!!";
            }
            else
            {
                int i;
                for (i = 0; i < listsanpham.Count; i++)
                {
                    i = i++;
                }
                ViewBag.soluong = i;
            }
            return View(listsanpham.ToPagedList(pageNumber, pageSize));
        }
        ///
        ///SẢN PHẨM THEO THƯƠNG HIỆU
        public ActionResult Thuonghieu()
        {
            var thuonghieu = from th in data.THUONGHIEUs select th;
            return PartialView(thuonghieu);
        }
        public ActionResult SPTheothuonghieu(int id, int? page)
        {
            // kiem tra thuong hieu co ton tai khong
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            THUONGHIEU thuonghieu = data.THUONGHIEUs.SingleOrDefault(n => n.MaTH == id);
            if (thuonghieu == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //truy xuat danh sach theo thuong hieu
            List<SANPHAM> listsanpham = data.SANPHAMs.Where(n => n.MaTH == id).OrderBy(n => n.GiaSP).ToList();
            if (listsanpham.Count == 0)
            {
                ViewBag.sanpham = "Thương hiệu này chưa mở bán!!";
            }
            else
            {
                int i;
                for (i = 0; i < listsanpham.Count; i++)
                {
                    i = i++;
                }
                ViewBag.soluong = i;
            }
            return View(listsanpham.ToPagedList(pageNumber, pageSize));
        }
    }
}

Do_An_Wed/Views/Giohang/DatHang.cshtml
@model IEnumerable<Do_An_Wed.Models.Giohang>

@{
    ViewBag.Title = "Đặt Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đặt hàng</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Masp)</th>
        <th>@Html.DisplayNameFor(model => model.tensanpham)</th>
        <th>@Html.DisplayNameFor(model => model.hinh)</th>
        <th>@Html.DisplayNameFor(model => model.giaban)</th>
        <th>@Html.DisplayNameFor(model => model.soluong)</th>
        <th>@Html.DisplayNameFor(model => model.dThanhTIen)</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Masp)</td>
            <td>@Html.DisplayFor(modelItem => item.tensanpham)</td>
            <td><img src="~/Content/img/@item.hinh" alt="hinh anh" width="180" /></td>
            @using (Html.BeginForm("CapNhatGioHang", "GioHang", new { @id = item.Masp }))
            {
                <td>@String.Format("{0:0,0}", item.giaban) VNĐ</td>
                <td>@Html.DisplayFor(modelItem => item.soluong)</td>
                <td>@Html.DisplayFor(modelItem => item.dThanhTIen)</td>
            }
        </tr>

    }
    <tr style="font-weight:bold; text-align:left; color:red">
        <td colspan="2">Số loại sách: @ViewBag.Tongsoluongsanpham</td>
        <td colspan="2">Số lượng sách: @ViewBag.Tongsoluong</td>
        <td colspan="4">Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien)</td>
    </tr>
    <tr style="font-weight:bold; color:red; text-align:right">
        <td colspan="6">
            @Html.ActionLink("Trở Về Giỏ Hàng", "GioHang", "GioHang")
        </td>
    </tr>
</table>

@using Do_An_Wed.Models
<h2 style="text-align:center; color:red">Thông Tin Đặt Hàng</h2>
@{
    KHACHHANG kh = (KHACHHANG)Session["TaikhoanCart"];
}
<
    <table class="center">


        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <tr style="height:40px">
                <td>Tên Khách Hàng: </td>
                <td style="font-weight:bold">@kh.HoTen</td>
            </tr>
            <tr style="height:40px">
                <td>Email: </td>
                <td style="font-weight:bold">@kh.EmailKH</td>
            </tr>
            <tr style="height:40px">
                <td>Địa chỉ : </td>
                <td style="font-weight:bold">@kh.DiachiKH</td>
            </tr>
            <tr style="height:40px">
                <td>Điện thoại: </td>
                <td style="font-weight:bold">@kh.DienthoaiKh</td>
            </tr>
            <tr style="height:40px">
                <td>Ngày đặt: </td>
                <td style="font-weight:bold">@DateTime.Now.ToShortDateString()</td>
            </tr>
            <tr style="height:40px">
                <td>Ngày giao: </td>
                <td style="font-weight:bold">
                    <input type="date" name="NgayGiao" />
                </td>
            </tr>

            <tr style="height:40px">
                <td> </td>
                <td style="font-weight:bold">
                    <input type="submit" value="Xác nhận" class="btn btn-success" />
                </td>
            </tr>
        }

    </table>

<style>
    table.center {
        margin-left: auto;
        margin-right: auto;
    }
</style>

Do_An_Wed/Views/Giohang/Giohang.cshtml
@model IEnumerable<Do_An_Wed.Models.Giohang>

@{ ViewBag.Title = "GioHang";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<h2>Giỏ Hàng</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Masp)</th>
        <th>@Html.DisplayNameFor(model => model.hinh)</th>
        <th>@Html.DisplayNameFor(model => model.giaban)</th>
        <th>@Html.DisplayNameFor(model => model.soluong)</th>
        <th>@Html.DisplayNameFor(model => model.dThanhTIen)</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@Html.DisplayFor(modelItem => item.Masp)</td>
    <td><img src="~/Content/img/@item.hinh" alt="hinh anh" width="180" /></td>
    @using (Html.BeginForm("Cannhapgiohang", "GioHang", new { @id = item.Masp }))
            {
                    <td>@String.Format("{0:0,0}", item.giaban) VNĐ</td>
                    <td><input type="number" min="1" name="txtSoLg" value="@item.soluong" /> </td>
                    <td>@Html.DisplayFor(modelItem => item.dThanhTIen)</td>
                    <td><a href="@Url.Action("Chitiet", "Sanphams", new {id = item.Masp})">Chi tiết</a> | @Html.ActionLink("Xóa", "XoaGioHang", new { @id = item.Masp })</td>
                    <td><input type="submit" value="Cập nhật" class="btn btn-success" /></td>
              }
</tr>}
    <tr style="font-weight:bold; text-align:left; color:red">
        <td colspan="2">Số loại sản phẩm: @ViewBag.Tongsoluongsanpham</td>
        <td colspan="2">Số lượng sản phẩm: @ViewBag.Tongsoluong</td>
        <td colspan="4">Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien)</td>
    </tr>
    <tr style="font-weight:bold; color:blue; text-align:right">
        <td colspan="5">
            @Html.ActionLink("Xóa Giỏ Hàng", "XoaTatCaGioHang")
        </td>
    </tr>
    <tr style="font-weight:bold; color:yellow; text-align:right">
        <td colspan="5">
            @Html.ActionLink("Đặt hàng", "DatHang", "GioHang")
        </td>
    </tr>
</table>

Do_An_Wed/Views/Giohang/GiohangPartial.cshtml
@if (Session["TaiKhoan"] == null)
{
<a href="/Account/Login" class="navbar-brand text-white " style="color; white; font-weight: bold; text-decoration: none;">
    Giỏ Hàng
</a>
}
else
{
<a href="/Giohang/Giohang" class="navbar-brand text-white " style="color; white; font-weight: bold; text-decoration: none;">
    Giỏ Hàng (@Session["TongSoSp"])
</a>
}

Do_An_Wed/Views/Giohang/XacNhanDonHang.cshtml
@{
    ViewBag.Title = "XacNhanDonHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="center">
    <h2 style="padding-bottom:300px;">Đơn hàng của bạn đã được ghi nhận lại và sẽ được giao đến cửa nhà của bạn sớm nhất có thể :))</h2>
</div>
<style>
    .center {
        text-align: center;
        margin-top: 200px;
    }

</style>